/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Articulo;
import modelo.Tienda;
import org.neodatis.odb.ODB;
import org.neodatis.odb.ODBFactory;
import org.neodatis.odb.Objects;
import org.neodatis.odb.core.query.IQuery;
import org.neodatis.odb.core.query.criteria.Where;
import org.neodatis.odb.impl.core.query.criteria.CriteriaQuery;

/**
 *
 * @author Joaquin
 */
public class JDModificarArticulo extends javax.swing.JDialog {
   static int a;
       ODB odbfac;
    String filename = "C:\\Users\\Joaquin\\Documents\\NetBeansProjects\\ODB\\src\\neodatis.test";

    /**
     * Creates new form JDModificarArticulo
     */
    public JDModificarArticulo(java.awt.Frame parent, boolean modal, int a) {
        super(parent, modal);
        initComponents();
        this.a=a;
        actualizarTiendas();
        rellenarCampos();
        
    }
    public void actualizarTiendas() {
        odbfac = ODBFactory.open(filename);
        jComboBoxTienda.removeAllItems();

        Objects<Tienda> objects = odbfac.getObjects(Tienda.class);
        if (objects.isEmpty()) {
            jComboBoxTienda.addItem("No hay Tiendas");
            jComboBoxTienda.setEnabled(false);
        } else {
            jComboBoxTienda.setEnabled(true);
            while (objects.hasNext()) {
                Tienda t = new Tienda();
                t = objects.next();
                jComboBoxTienda.addItem(String.valueOf(t.getId()));

            }
        }
        odbfac.close();

    }
    public void rellenarCampos(){
        odbfac=ODBFactory.open(filename);
        IQuery query = new CriteriaQuery(Articulo.class, Where.equal("id", a));
        Objects<Articulo> objects = odbfac.getObjects(query);
        Articulo art = objects.getFirst();
        jTextFieldDescripcionArticulo.setText(art.getDescripcion());
        jTextFieldNombreArticulo.setText(art.getNombre());
        jTextFieldPrecioArticulo.setText(art.getPrecio()+"");
        jLabelAntTienda.setText(art.getTiendaId()+"");
        System.out.println(art.getTiendaId());
       // jComboBoxTienda.setSelectedItem(art.getTiendaId());
        
        odbfac.close();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNombreArticulo = new javax.swing.JTextField();
        jTextFieldDescripcionArticulo = new javax.swing.JTextField();
        jTextFieldPrecioArticulo = new javax.swing.JTextField();
        jButtonModificarArticulo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxTienda = new javax.swing.JComboBox<>();
        jLabelAntTienda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextFieldNombreArticulo.setText("jTextField1");

        jTextFieldDescripcionArticulo.setText("jTextField2");

        jTextFieldPrecioArticulo.setText("jTextField3");

        jButtonModificarArticulo.setText("Modificar");
        jButtonModificarArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarArticuloActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripcion");

        jLabel3.setText("Precio");

        jLabel4.setText("Tienda");

        jComboBoxTienda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelAntTienda.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButtonModificarArticulo)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAntTienda)
                        .addGap(22, 22, 22)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldNombreArticulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldDescripcionArticulo, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPrecioArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                    .addComponent(jComboBoxTienda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNombreArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescripcionArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecioArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelAntTienda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jButtonModificarArticulo)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarArticuloActionPerformed
        // TODO add your handling code here:
        odbfac = ODBFactory.open(filename);
        IQuery queryupdate = new CriteriaQuery(Articulo.class, Where.equal("id", a));
        Objects<Articulo> objects = odbfac.getObjects(queryupdate);
        Articulo art = objects.getFirst();
        art.setDescripcion(jTextFieldDescripcionArticulo.getText());
        art.setNombre(jTextFieldNombreArticulo.getText());
        art.setTiendaId(Integer.parseInt(jComboBoxTienda.getSelectedItem().toString()));
        art.setId(a);
        art.setPrecio(Double.parseDouble(jTextFieldPrecioArticulo.getText()));
        odbfac.store(art);
        odbfac.close();
        System.out.println("modificao");
        
        
       
    }//GEN-LAST:event_jButtonModificarArticuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDModificarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDModificarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDModificarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDModificarArticulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDModificarArticulo dialog = new JDModificarArticulo(new javax.swing.JFrame(), true, a);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificarArticulo;
    private javax.swing.JComboBox<String> jComboBoxTienda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAntTienda;
    private javax.swing.JTextField jTextFieldDescripcionArticulo;
    private javax.swing.JTextField jTextFieldNombreArticulo;
    private javax.swing.JTextField jTextFieldPrecioArticulo;
    // End of variables declaration//GEN-END:variables
}
